name: Staging

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request_review:
    types: [ submitted ]
  workflow_dispatch:

jobs:
  build:
    if: (github.event.pull_request.base.ref == 'master' && github.event.review.state == 'approved') || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-22.04
    outputs:
      IMAGE_TAG: ${{ steps.docker_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Akto code analysis
        uses: akto-api-security/code-analysis-action@v1.0.2
        with:
          AKTO_DASHBOARD_URL: https://app.akto.io
          AKTO_API_KEY: miGSJAnh07c345EVVfjPNSn9jxJR1VspZgcgqLyl
          API_COLLECTION_NAME: aryan-temp
